/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import swing.ScrollBar;
import java.awt.Color;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author LaptopcuaThanh
 */
public class chatbody extends javax.swing.JPanel {

    /**
     * Creates new form chattittle
     */
    public chatbody() {
        initComponents();
        init();
        addItemleft("\"aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo alo alo","Thanh");
        addItemright("aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo aloalo alo alo");
        addDate("11/11/2022");
        addItemright("a Text ở đây");
        addItemright("alo alo");
    }

    private void init() {
        body.setLayout(new MigLayout("fillx", "", "5[]5"));
        sp.setVerticalScrollBar(new ScrollBar());
        sp.getVerticalScrollBar().setBackground(Color.WHITE);
    }

    public void addItemleft(String text, String user) {
        int index=50;
        while(index<text.length())
        {
            index = text.indexOf(' ', index); 
            text = text.substring(0, index) + "\n" + text.substring(index+1, text.length());
            index+=50;
        }
        chatleftwithprofile item = new chatleftwithprofile();
        item.setText(text);
        item.setUserProfile(user);
        body.add(item, "wrap, w 100::80%");
        //  ::80% set max with 80%
        body.repaint();
        body.revalidate();

    }

    public void addItemright(String text) {
        int index=50;
        while(index<text.length())
        {
            index = text.indexOf(' ', index); 
            text = text.substring(0, index) + "\n" + text.substring(index+1, text.length());
            index+=50;
        }
        chatright item = new chatright();
        item.setText(text);
        body.add(item, "wrap, al right");
//                + ", w 100::80");
        
        body.repaint();
        body.revalidate();

    }
    
    public void addDate(String date) {
        chatdate item = new chatdate();
        item.setDate(date);
        body.add(item, "wrap, al center");
        body.repaint();
        body.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();

        setBackground(new java.awt.Color(230, 230, 230));

        sp.setBorder(null);

        body.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        sp.setViewportView(body);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
